📝 Community driven `Websurfx` instances page
neon-mmd/websurfx pull request #253
Opened 2023-09-21 14:25 UTC by neon-mmd

## What does this PR do?

This PR provides an instances page in the `docs` which provides all the instances maintained by the `Websurfx` community and by the `Websurfx` project. 

## Why is this change important?

This PR is essential as this provides the user the ability to use and try the project by using the provided instances. 

## Author's checklist

- [x] Provide an instances page in the `docs`.
- [x] Bump the app version to `v0.21.5` 

## Related issues

Closes #252

2023-09-21 14:54 UTC, alamin655 commented on docs/instances.md
> +> To contribute your server instance checkout the contributing guide [here](https://github.com/neon-mmd/websurfx/blob/HEAD/CONTRIBUTING.md).
```suggestion
> To contribute your server instance, check out the contributing guide [here](https://github.com/neon-mmd/websurfx/blob/HEAD/CONTRIBUTING.md).
```

2023-09-21 14:55 UTC, alamin655 commented on docs/instances.md
> +|https://alamin655-websurfx.hf.space/|www|v0.21.4|🇺🇸US||✅|✅|||
```suggestion
| URL                                       | Network | Version | Location | Behind Cloudflare? | Official | TLS | IPv6 | Comment |
|-------------------------------------------|---------|---------|----------|--------------------|----------|-----|------|---------|
| https://alamin655-websurfx.hf.space/      | www     | v0.21.4 | 🇮🇳 IN  |                    | ✅       | ✅  |      |         |
```

2023-09-21 15:01 UTC, alamin655 requested changes
Consider replacing `Official` with `Maintained by` to clarify the instance's maintainer. This change will enhance transparency in the list.

2023-09-21 15:09 UTC, neon-mmd commented on docs/instances.md
> +> To contribute your server instance checkout the contributing guide [here](https://github.com/neon-mmd/websurfx/blob/HEAD/CONTRIBUTING.md).
Thanks :heart: for taking the time reviewing this PR. I will make the suggested changes right away :rocket: :slightly_smiling_face: .

2023-09-21 15:25 UTC, neon-mmd commented
> Consider replacing `Official` with `Maintained by` to clarify the instance's maintainer. This change will enhance transparency in the list.

I think I agree with your point, but I think we can have it more of an optional requirement because I think some people might not feel very great sharing their profile. What do you say ? :slightly_smiling_face:

2023-09-22 05:11 UTC, alamin655 approved these changes
Approved! Let's merge this in. 👍

2023-09-22 05:11 UTC, merged