Implement Qwant search engine support
neon-mmd/websurfx pull request #605
Opened 2024-09-07 15:00 UTC by nrabulinski

## What does this PR do?

Implements the Qwant search engine support

## Why is this change important?

I wanted to contribute the Qwant search engine support

## How to test this PR locally?

Run websurfx and enable the Qwant search engine

## Additional notes

Sometimes, requesting results from Qwant fails. So far I've encountered error 22 which I don't know what it means, and error 27 which means completing a captcha is required. Second request pretty much always works for me though. Not sure if that's an acceptable state, if not, I'm happy to potentially help with captcha implementation.

This search engine is implemented using the API, contrary to other ones which use scripting. That's because Qwant's frontend is not paginated and there's no way to force it to be, so I couldn't scrape more than one page worth of results. And because of that I decided to just use the API itself.

## Related issues

Closes #317

2024-09-07 17:38 UTC, neon-mmd requested changes
Thanks :heart: for working on such a wonderful PR. Good job!! Keep it up!! 👍 But before we merge this PR in, I would like to suggest a few changes. 🙂

2024-09-07 17:38 UTC, neon-mmd commented on src/engines/qwant.rs
> +            .change_context(EngineError::RequestError)?;
I think you could have used the already available `json_as_bytes_from_upstream` function to fetch data and deserialize it using something like `bincode`. What do you think? 🙂 .

2024-11-03 18:16 UTC, neon-mmd commented
@nrabulinski It has been a week. Any updates on this draft PR? 🙂 .

2024-12-05 20:27 UTC, neon-mmd commented
@nrabulinski It has been a month. Any updates on this draft PR? 😅

2025-04-18 18:49 UTC, neon-mmd commented
@nrabulinski It has been a long time. Any updates on this? 🙂

2026-01-17 09:13 UTC, neon-mmd commented on src/engines/qwant.rs
> +            .change_context(EngineError::RequestError)?;
After testing this on my side, I found that this doesn't work and it is not feasible that's why I am marking this as resolved.

Also, we would suggest to drop this idea as well as it is not feasable (not possible) to implement. 😅

2026-01-17 09:14 UTC, neon-mmd commented
@jfvillablanca 
Sorry for the ping.

This draft seems to be pending for a long long time and the person behind it seems unresponsive. 

So if you are not busy and interested to work on this draft. We would suggest letting us know. So that we will assign this to you. 🙂

2026-04-10 11:53 UTC, neon-mmd commented
@metamorphosis-dev 
Sorry for ping but would you be interested to take this work up? Like we will assign the PR to you. Then you can just clone this fork (below  and work on it and keep pushing the changes. 

```
git clone https://github.com/nrabulinski/websurfx.git websurfx-nrabulinski
cd websurfx-nrabulinski
echo "continue working here";
```

2026-04-10 12:17 UTC, ghost commented
Sure thing! I'll take a look at the existing work on this and pick it up. Will rebase onto rolling and bring it in line with the current engine patterns. Should have something up soon 👍

2026-04-10 13:04 UTC, neon-mmd commented
> Sure thing! I'll take a look at the existing work on this and pick it up. Will rebase onto rolling and bring it in line with the current engine patterns. Should have something up soon 👍

Yes, that would be better. Also, not sure why @nrabulinski left this in the middle. No idea. Maybe they had a change of heart not sure but here you go, it is passed over to you. :wink:. Make sure to do your dark spell and get `qwant` follow our orders.

2026-04-15 20:50 UTC, neon-mmd commented
@nrabulinski 
Sorry for the ping and sorry but we are closing this PR since you have not provided any updates on it for a very very long time. So we made a new PR taking some of your work and Franz Kafka's work and crediting you both as well as implementing whatever else is required. So we would suggest checking the new PR #784 out and if you could help test the new PR.

---
Without a good engine, a cruise ship doesn't sail the sea very nicely. So had to be perfected for a happy fulfilling ride.

2026-04-15 20:50 UTC, closed without merging