:sparkles: Clear button for the search bar
neon-mmd/websurfx pull request #608
Opened 2024-09-29 19:24 UTC by neon-mmd

## What does this PR do?

This PR provides a clear button for the search bar on the home and search pages and also disables the webkit unstable and very incompatible webkit search and clear buttons.

## Why is this change important?

This change is essential as it provides a clear button to easily and quickly clear the search bar text. By providing this change it improves user experience.

## Screenshots

### Home/Root/Index Page
![image](https://github.com/user-attachments/assets/8693163a-5619-4601-ae41-35a79c5477d6)

### Search Page
![image](https://github.com/user-attachments/assets/9b6b57ce-468b-47ad-bbb5-96db1f05c83a)

## How to test this PR locally?

It can be tested by installing and running `Websurfx` as mentioned in the `docs` and on the `readme` and by launching the browser and thoroughly testing. By testing whether the clear button clears the search bar text when it is clicked.

## Author's checklist

- [x] Provide a clear button for the search bar.
- [x] Disable the unstable webkit search and clear buttons
- [x] Bump the app version to `v1.18.0`

## Related issues

Closes #394

2024-10-03 09:40 UTC, jfvillablanca requested changes

2024-10-03 09:40 UTC, jfvillablanca commented on public/static/themes/simple.css
> +.search_bar input::webit::-webkit-search-cancel-button{
```suggestion
.search_bar input::-webkit-search-cancel-button{
```

2024-10-03 10:40 UTC, neon-mmd commented on public/static/themes/simple.css
> +.search_bar input::webit::-webkit-search-cancel-button{
Ok I see, I am sorry for this silly one but I will fix this right away. Also thanks :heart: for pointing this out. :slightly_smiling_face:

2024-10-06 14:39 UTC, spencerjibz approved these changes

2024-10-08 12:03 UTC, jfvillablanca approved these changes

2024-10-08 12:09 UTC, merged